name: mindverse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5

environment:
  sdk: '>=3.0.2 <4.0.0'

flutter_native_splash:
  color: "#ececec"
  image: mindVerse.png
  android_gravity: top

dependencies:
  any_link_preview: ^3.0.0
  appwrite: 8.2.0
  auto_size_text: ^3.0.0
  chewie: ^1.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  video_player: ^2.6.1
  flutter_native_splash: ^2.3.1
  flutter_staggered_grid_view: ^0.6.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  timeago: ^3.4.0
  uuid: ^3.0.7
  url_launcher: ^6.1.10
  visibility_detector: ^0.3.3
  photo_view: ^0.14.0
  sliding_up_panel: ^2.0.0+1
  flutter_keyboard_visibility: ^5.4.1
  lottie: ^2.4.0
  flutter_contacts: ^1.1.6
  image_picker: ^0.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/lottie/
